# Generated by Django 6.0.5 on 2026-05-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0006_comment_task_id_alter_attachment_task_id'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='interaction.tag'),
        ),
    ]
