# Generated by Django 6.0.5 on 2026-05-23 07:18

import interaction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=interaction.models.upload_path),
        ),
        migrations.AddField(
            model_name='attachment',
            name='task_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
