# Generated by Django 6.0.5 on 2026-05-24 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0005_attachment_file_attachment_task_id'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workflows.task'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workflows.task'),
        ),
    ]
