# Generated by Django 6.0.5 on 2026-05-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0006_comment_task_id_alter_attachment_task_id'),
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'studio')},
        ),
    ]
