<<<<<<< HEAD
# Generated by Django 6.0.5 on 2026-05-21 06:26

import django.db.models.deletion
from django.conf import settings
=======
# Generated by Django 6.0.5 on 2026-05-19 12:00

>>>>>>> stun
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> stun
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name='StudioMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Studio Admin'), ('LEAD', 'Project Lead'), ('DESIGNER', 'Designer'), ('WRITER', 'Writer'), ('REVIEWER', 'Reviewer'), ('VIEWER', 'Client Viewer')], max_length=10)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studios.studio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'studio')},
            },
        ),
=======
>>>>>>> stun
    ]
